"""Write every scenario's fixtures to disk, then run the real arxml-secdiff CLI
against each before/after pair and collect the actual verdicts."""

from __future__ import annotations

import json
import os
import subprocess
import sys

sys.path.insert(0, os.path.dirname(__file__))

from generate_scenarios import build_arxml, build_roles  # noqa: E402
from scenario_defs import SCENARIOS  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
PY = os.path.join(os.path.dirname(HERE), ".venv", "bin", "python3")


def main() -> None:
    rows = []
    for scn in SCENARIOS:
        d = os.path.join(HERE, scn.id)
        os.makedirs(d, exist_ok=True)

        before_path = os.path.join(d, "before.arxml")
        after_path = os.path.join(d, "after.arxml")
        roles_path = os.path.join(d, "roles.yaml")

        with open(before_path, "w") as f:
            f.write(build_arxml(scn, scn.before_nodes, scn.before_edges))
        with open(after_path, "w") as f:
            f.write(build_arxml(scn, scn.after_nodes, scn.after_edges))
        with open(roles_path, "w") as f:
            f.write(build_roles(scn, scn.before_nodes))

        notes_path = os.path.join(d, "NOTES.md")
        with open(notes_path, "w") as f:
            f.write(
                f"# {scn.title}\n\n"
                f"**Source:** {scn.source}\n\n"
                f"**Summary:** {scn.summary}\n\n"
                f"**Expected verdict on the update (before -> after):** {scn.expected_after}\n"
            )

        cmd = [
            PY, "-m", "arxml_secdiff.cli",
            "--before", before_path,
            "--updated", after_path,
            "--roles", roles_path,
            "--format", "json",
        ]
        proc = subprocess.run(cmd, capture_output=True, text=True, cwd=os.path.dirname(HERE))

        row = {
            "id": scn.id,
            "title": scn.title,
            "expected": scn.expected_after,
            "exit_code": proc.returncode,
            "stderr": proc.stderr.strip()[-800:] if proc.returncode not in (0, 1, 2, 3) else "",
        }
        try:
            data = json.loads(proc.stdout)
            row["verdict"] = data.get("verdict")
            row["risk"] = data.get("max_risk") or data.get("risk")
            findings = data.get("findings", [])
            row["n_findings"] = len(findings)
            row["categories"] = sorted({f.get("category") for f in findings})
        except Exception as e:  # noqa: BLE001
            row["verdict"] = f"PARSE_ERROR: {e}"
            row["risk"] = None
            row["n_findings"] = None
            row["categories"] = []

        with open(os.path.join(d, "cli_output.json"), "w") as f:
            f.write(proc.stdout)
        if proc.stderr:
            with open(os.path.join(d, "cli_stderr.txt"), "w") as f:
                f.write(proc.stderr)

        rows.append(row)
        print(f"{scn.id:28s} expected={scn.expected_after:5s} actual={row['verdict']!s:14s} "
              f"findings={row['n_findings']} exit={proc.returncode}")

    with open(os.path.join(HERE, "results.json"), "w") as f:
        json.dump(rows, f, indent=2)

    # -- markdown summary --------------------------------------------------
    lines = [
        "# Real-world-inspired scenario test results",
        "",
        "Generated by running the actual `arxml-secdiff` CLI against each before/after",
        "ARXML pair below. `match` is True when the tool's actual verdict is at least as",
        "strict as expected (BLOCK satisfies an expectation of FLAG or BLOCK, etc.) --",
        "see `results.json` for the raw data and each scenario's folder for the full",
        "CLI JSON output, the fixtures themselves, and sourcing notes.",
        "",
        "| # | Scenario | Expected | Actual verdict | Findings | Categories | Match |",
        "|---|---|---|---|---|---|---|",
    ]
    rank = {"PASS": 0, "FLAG": 1, "INCONCLUSIVE": 1, "BLOCK": 2}
    for i, row in enumerate(rows, 1):
        exp = row["expected"]
        act = str(row["verdict"])
        match = "?"
        if act in rank and exp in rank:
            match = "yes" if rank[act] >= rank[exp] or act == exp else "no"
        cats = ", ".join(row["categories"]) if row["categories"] else "-"
        lines.append(
            f"| {i} | {row['title']} | {exp} | {act} | {row['n_findings']} | {cats} | {match} |"
        )
    with open(os.path.join(HERE, "RESULTS.md"), "w") as f:
        f.write("\n".join(lines) + "\n")

    print("\nWrote scenarios/RESULTS.md and scenarios/results.json")


if __name__ == "__main__":
    main()
